### ISSUE TITLE
issue - Error

### ISSUE THREAD

**Issue by random-robbie** [tr4l/iframeBusterXSS#1]
Any ideas why it's doing this.

```
root@0c4b9041ebae:/iframeBusterXSS# ./check.rb -r http://facebook.com
Root path: http://facebook.com
/usr/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect': Failed to open TCP connection to facebook.compredicta:80 (getaddrinfo: Name or service not known) (Faraday::ConnectionFailed)
	from /usr/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
	from /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	from /usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
	from /usr/lib/ruby/2.3.0/net/http.rb:1398:in `request'
	from /usr/lib/ruby/2.3.0/net/http.rb:1156:in `get'
	from /var/lib/gems/2.3.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:85:in `perform_request'
	from /var/lib/gems/2.3.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:43:in `block in call'
	from /var/lib/gems/2.3.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
	from /var/lib/gems/2.3.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:38:in `call'
	from /var/lib/gems/2.3.0/gems/faraday-0.15.4/lib/faraday/request/url_encoded.rb:15:in `call'
	from /var/lib/gems/2.3.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
	from /var/lib/gems/2.3.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
	from /var/lib/gems/2.3.0/gems/faraday-0.15.4/lib/faraday/connection.rb:138:in `get'
	from ./check.rb:21:in `check_xss'
	from ./check.rb:41:in `<main>'
root@0c4b9041ebae:/iframeBusterXSS#
```

**Comment by tr4l** [comment]
Hi,

Sorry the final "/" on the url is mandatory. I will probably fix that on a later release.

Please try:
./check.rb -r http://facebook.com/
instead.
Also, facebook will probably work better in http's' and with a full domain (www. or other)

**Comment by random-robbie** [comment]
ah perfect thank you for the fast response!
